Implemented SWIG tests.

diff --git a/src/souffle-compile.in b/src/souffle-compile.in
--- a/src/souffle-compile.in
+++ b/src/souffle-compile.in
@@ -10,9 +10,6 @@
 # script that compiles a generated C++ program and executes it
 #
 
-# Error out if any of the subcommands fail
-set -e
-
 # Show usage
 usage() {
   printf "Name:
@@ -125,6 +122,9 @@ cd "$OLDPWD"
 # Make temp folder and copy relevant files there
 if [ -n "$SWIGLANG" ]
 then
+  # Error out if any of the subcommands fail
+  set -e
+
   # set environment variables
   # directory where swig interface files are in souffle
   TMP_DIR="$(mktemp -d)"
@@ -147,19 +147,30 @@ then
   # Checks input language and compiles files with local python3 config or local java_home config
   if [ "$SWIGLANG" = "python" ]
   then
-    $CXX -fPIC -c -D__EMBEDDED_SOUFFLE__ $CXXFLAGS $CPPFLAGS SwigInterface_wrap.cxx $dir/$exe.cpp $(python3-config --cflags) $HEADER_DIRS 2>&1
-    $CXX -shared SwigInterface_wrap.o $exe.o $(python3-config --ldflags) -o _SwigInterface.so $LIBS -lstdc++
+    # Python adds -Wall -Wextra
+    PYTHON_FLAGS=$(python3-config --cflags | sed 's/-Wall\|-Wextra//g')
+    $CXX -fPIC -c -D__EMBEDDED_SOUFFLE__ $CXXFLAGS $CPPFLAGS SwigInterface_wrap.cxx $dir/$exe.cpp -Wformat $PYTHON_FLAGS $HEADER_DIRS 2>&1
+    $CXX -shared $CXXFLAGS $CPPFLAGS SwigInterface_wrap.o $exe.o $(python3-config --ldflags) -o _SwigInterface.so $LDFLAGS $LIBS -lstdc++
   elif [ "$SWIGLANG" = "java" ]
   then
-    JAVADIR="$(printenv JAVA_HOME || java -XshowSettings:properties -version 2>&1 | grep java.home | sed 's/^.*= //')"
+    CMAKE_JAVA_JNI="@SOUFFLE_JAVA_INCLUDE_PATH@"
 
-    if [ -z "$JAVADIR" ]
-    then
-      error "JAVA_HOME environment variable has not been set"
+    if [ -z $CMAKE_JAVA_JNI ]; then
+      JAVADIR="$(printenv JAVA_HOME || java -XshowSettings:properties -version 2>&1 | grep java.home | sed 's/^.*= //')"
+
+      if [ -z "$JAVADIR" ]
+      then
+        error "JAVA_HOME environment variable has not been set"
+      fi
+
+      JNI_INCLUDES=-I$JAVADIR -I$JAVADIR/include -I$JAVADIR/include/linux  -I$JAVADIR/include/darwin
+
+    else
+      JNI_INCLUDES=$(echo "$CMAKE_JAVA_JNI" | sed 's/^\|;/ -I/g')
     fi
 
-    $CXX -fPIC -c -D__EMBEDDED_SOUFFLE__ $CXXFLAGS $CPPFLAGS SwigInterface_wrap.cxx $dir/$exe.cpp -I$JAVADIR -I$JAVADIR/include -I$JAVADIR/include/linux  -I$JAVADIR/include/darwin -I/usr/lib/x86_64-linux-gnu/ $HEADER_DIRS 2>&1
-    $CXX -shared SwigInterface_wrap.o $exe.o -o libSwigInterface.so $LIBS -lstdc++
+    $CXX -fPIC -c -D__EMBEDDED_SOUFFLE__ $CXXFLAGS $CPPFLAGS SwigInterface_wrap.cxx $dir/$exe.cpp $JNI_INCLUDES -I/usr/lib/x86_64-linux-gnu/ $HEADER_DIRS 2>&1
+    $CXX -shared $CXXFLAGS $CPPFLAGS SwigInterface_wrap.o $exe.o -o libSwigInterface.so $LDFLAGS $LIBS -lstdc++
   fi
 
   # move generated files to same directory as cpp file
